<#

DO NOT EDIT THIS FILE WHEN IT IS LOCATED AT THE DEFAULT c:\scripts\CognosDownloader\CognosDefaults.ps1.
You need to copy this template to c:\scripts\CognosDefaults.ps1.

Per the suggested install instructions you should use the path c:\scripts\CognosDownload.ps1 for calling
the CognosDownloader.  It will use the CognosDefaults.ps1 file from the same folder.

This file overrides ANY variable you set on the commandline for CognosDownload.ps1
Uncomment any sections you need below.

#>

#Only set this if no other users in your domain need the script
#$username = '0000username'

#Your DSN for your district.
#$espdsn = 'schoolsms' #Recommend to set this

#Override password file path.
#$passwordfile = 'c:\scripts\mysavedpassword.txt'

#If you always want to save to the same path.
#$savepath = 'c:\scripts\files'

#eFinance DSN
#$efpdsn = 'schoolfms' #Recommend to set this

#eFinance User
#$efpuser = 'efinanceusername'

#Email Configuration so you don't have to put it on the command line. Still need to specify -SendMail on command line.
#$mailfrom = "from@yourdomain.com"
#$mailto="technology@yourdomain.com"
#$smtpserver="smtp-relay.gmail.com"
#$smtpport="587"
#$smtppasswordfile="C:\Scripts\emailpw.txt" #change to a file path for email server password not needed if you use smtp-relay and auth your public IPs

<#
Example for multiuser environment where the scripts are running under the same Windows Accounts. All of these password files would be decryptable under
the same account. You can specify any variable from above in the switch statement.
No Default needed as it will be specified at the command line, above, or default in CognosDownload.ps1
#>

# switch($username){
#     '0401cmillsap' {
#         $useranme = '0403cmillsap'    
#         $efpuser = 'cmillsap'
#         $passwordfile = 'c:\scripts\0403cmillsap-password.txt'
#         $SendMail = $True
#     }
#     '0402cweber' {
#         $efpuser = $username;
#         $passwordfile = 'c:\scripts\0402cweber-password.txt';
#         $savepath = "c:\scripts\ImportFiles"
#     }
#     'SSOusername' { 
#         $efpuser =''
#         $passwordfile = 'c:\scripts\importfiles\scripts\userpw1.txt'
#         $savepath = "c:\users\cmillsap\Downloads"
#     }
#     'SSOusername2' {
#         $efpuser = ''
#         $passwordfile = 'c:\scripts\importfiles\scripts\userpw1.txt'
#     }
# }

<#
Example of a multiple user environment where the scripts are running under different Windows Accounts. You can specify the individual Windows Accounts and their eSchool
username, dsn, password path, etc.
#>

# switch($env:username) {
#   'xyz_automation' { $username = '0401cmillsap'; $passwordfile = 'c:\script\cmillsappw.txt'; $espdsn = 'gentrysms' }
#   'abc_domain_admin' { $username = '0401jmillsap'; $passwordfile = 'c:\scripts\jmillsappw.txt'; $espdsn = 'gentrysms' }
# }

<#
Empty CSV files fail the CSV Verification as they don't contain any data to verify. You can add reports by name to this variable and it will bypass the CSV verification process.
#>

# $ignoreEmptyCSV = @('Report Name 1','Report_Name_2')
# if ($ignoreEmptyCSV -contains $report) { $DisableCSVVerification = $True }

<#
Do not download/process these reports during the summer months (June and July).
Modify as you need.
#>

# if (@(6,7) -contains ([int](Get-Date -Format MM))) {
#     $SkipTheseReports = @('Report Name 1','Report_Name_2')
#     Write-Host "Info: Skip downloading this file per the CognosDefaults.ps1" -ForegroundColor Green
#     if ($SkipTheseReports -contains $report) { $SkipDownloadingFile = $True }
# }

<#
Linux set path
#>
# if (-Not($IsWindows)) {
#     $savepath = '/scripts/download'
#     $passwordfile = '/scripts/mypassword.txt'
# }